<?
$PERM["/"]["16"]="W";
$PERM["/"]["*"]="R";
$PERM["bitrix"]["16"]="W";
$PERM["local"]["14"]="X";
$PERM["personal"]["9"]="W";
$PERM["personal"]["8"]="W";
$PERM["catalog"]["9"]="W";
$PERM["catalog"]["8"]="W";
$PERM["news"]["9"]="W";
$PERM["news"]["8"]="W";
$PERM["about"]["9"]="W";
$PERM["about"]["8"]="W";
$PERM["index.php"]["9"]="W";
$PERM["index.php"]["8"]="W";
$PERM["desktop_app"]["*"]="D";
$PERM["online"]["*"]="R";
$PERM["pub"]["5"]="T_8";
$PERM["upload"]["5"]="T_8";
?>