<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Фотопечать");
$APPLICATION->SetPageProperty('description', 'Выбор из 600 вариантов фотопечати для дверей шкафов-купе. Скачайте наши каталоги и найдите идеальное изображение для вашего 2-дверного, 3-дверного или углового шкафа.');
?><p>
Каталог фотопечати — подборка изображений для фасадов 2-дверных, 3-дверных и угловых шкафов-купе. Скачайте наши каталоги, чтобы выбрать фотопечать для дверей вашего шкафа-купе из 600 вариантов.
</p>

<div style="margin-bottom:32px;" class="item-views items-list1 documents-mode  list list-type-block  image_left documents">
	<div class="group-content">
		<div class="row sid items ">
			<div class=" col-md-12">
				<div class="item colored_theme_hover_bg-block  wti box-shadow bordered clearfix" >
					<div class="file_type pdf">
						<i class="icon"></i>
					</div>
					<div class="body-info">
					<div class="title">
						<a href="/upload/files/photoprinting_catalog.pdf" class="dark-color " data-caption="Скачать каталог фотопечати" target="_blank">	
							Скачать каталог фотопечати	
						</a>	
						<div class="size muted font_xs">41.57 Мб</div>
					</div>
					<div class="properties"></div>
						<a href="/upload/files/photoprinting_catalog.pdf" class="colored_theme_hover_bg-el bordered dark-color rounded3 muted download_wrap" data-caption="Скачать каталог фотопечати" target="_blank">	
							<i class="svg inline  svg-inline-download-arrow" aria-hidden="true">
								<svg xmlns="http://www.w3.org/2000/svg" width="10" height="15" viewBox="0 0 10 15"><defs><style>.cls-1{fill:#b8b8b8;fill-rule:evenodd}</style></defs><path data-name="Rounded Rectangle 853 copy" class="cls-1" d="M256.717,755.686l-4.027,4.031c-0.006.006-.015,0.008-0.021,0.014a1.007,1.007,0,0,1-.29.191h0a0.973,0.973,0,0,1-.52.06,0.79,0.79,0,0,1-.106-0.02,0.968,0.968,0,0,1-.473-0.245l-3.993-4.031a0.984,0.984,0,0,1,0-1.4,1,1,0,0,1,1.41,0l2.3,2.325V749a1,1,0,0,1,2,0v7.6l2.308-2.31a1,1,0,0,1,1.409,0A0.986,0.986,0,0,1,256.717,755.686ZM248,761h8a1,1,0,0,1,0,2h-8A1,1,0,0,1,248,761Z" transform="translate(-247 -748)"></path></svg>
							</i>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="s-list-section">
	<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.section.list", 
	"sections_compact_photoprint", 
	array(
		"ADD_SECTIONS_CHAIN" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "N",
		"COUNT_ELEMENTS" => "Y",
		"COUNT_ELEMENTS_FILTER" => "CNT_ACTIVE",
		"FILTER_NAME" => "sectionsFilter",
		"IBLOCK_ID" => "39",
		"IBLOCK_TYPE" => "aspro_max_content",
		"SECTION_CODE" => "",
		"SECTION_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"SHOW_PARENT_NAME" => "Y",
		"TOP_DEPTH" => "1",
		"VIEW_MODE" => "LINE",
		"COMPONENT_TEMPLATE" => "sections_compact_photoprint",
		"TITLE_BLOCK" => "Новости",
		"TITLE_BLOCK_ALL" => "Все новости",
		"ALL_URL" => "company/news/",
		"SORT" => "SORT",
		"SORT_ORDER" => "ASC",
		"SORT_2" => "ID",
		"SORT_ORDER_2" => "ASC",
		"TITLE_BLOCK_SHOW" => "Y",
		"NO_MARGIN" => "Y",
		"SECTION_ID" => $_REQUEST["SECTION_ID"]
	),
	false
);?>
</div>


 <?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"photoprint-catalog", 
	array(
		"ADD_DETAIL_TO_SLIDER" => "Y",
		"ADD_ELEMENT_CHAIN" => "N",
		"ADD_PICT_PROP" => "",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"ALSO_ITEMS_COUNT" => "5",
		"ALSO_ITEMS_POSITION" => "bottom",
		"BG_POSITION" => "top left",
		"BLOCK_BLOG_NAME" => "",
		"BLOCK_BRANDS_NAME" => "",
		"BLOCK_LANDINGS_NAME" => "",
		"BLOCK_NEWS_NAME" => "",
		"BLOCK_PARTNERS_NAME" => "",
		"BLOCK_PROJECTS_NAME" => "",
		"BLOCK_REVIEWS_NAME" => "",
		"BLOCK_SALE_NAME" => "",
		"BLOCK_SERVICES_NAME" => "",
		"BLOCK_STAFF_NAME" => "",
		"BLOCK_TIZERS_NAME" => "",
		"BLOCK_VACANCY_NAME" => "",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COLOR_NEW" => "3E74E6",
		"COLOR_OLD" => "C0C0C0",
		"COMPONENT_TEMPLATE" => "photoprint-catalog",
		"CONVERT_CURRENCY" => "N",
		"COUNT_IN_LINE" => "3",
		"CURRENCY_ID" => "RUB",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_BLOCKS_ALL_ORDER" => "tizers,form_order,desc,goods,char,gallery,docs,services,news,vacancy,blog,reviews,projects,partners,staff,brands,landings,comments",
		"DETAIL_BLOG_USE" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FB_USE" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_LINKED_GOODS_SLIDER" => "Y",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_USE_COMMENTS" => "Y",
		"DETAIL_VK_USE" => "N",
		"DISPLAY_AS_RATING" => "rating",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_LINKED_PAGER" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_WISH_BUTTONS" => "Y",
		"ELEMENT_TYPE_VIEW" => "element_1",
		"FONT_MAX" => "50",
		"FONT_MIN" => "10",
		"FORM_ID_ORDER_SERVISE" => "",
		"GALLERY_TYPE" => "small",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"HIDE_SECTION_NAME" => "N",
		"IBLOCK_CATALOG_ID" => "1",
		"IBLOCK_CATALOG_TYPE" => "-",
		"IBLOCK_ID" => "39",
		"IBLOCK_LINK_BLOG_ID" => "",
		"IBLOCK_LINK_BRANDS_ID" => "",
		"IBLOCK_LINK_LANDINGS_ID" => "",
		"IBLOCK_LINK_NEWS_ID" => "",
		"IBLOCK_LINK_PARTNERS_ID" => "",
		"IBLOCK_LINK_PROJECTS_ID" => "",
		"IBLOCK_LINK_REVIEWS_ID" => "",
		"IBLOCK_LINK_SALE_ID" => "",
		"IBLOCK_LINK_SERVICES_ID" => "",
		"IBLOCK_LINK_STAFF_ID" => "",
		"IBLOCK_LINK_TIZERS_ID" => "",
		"IBLOCK_LINK_VACANCY_ID" => "",
		"IBLOCK_TYPE" => "aspro_max_content",
		"IMAGE_CATALOG_POSITION" => "left",
		"IMAGE_POSITION" => "left",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LANDING_IBLOCK_ID" => "",
		"LANDING_SECTION_COUNT" => "10",
		"LANDING_TITLE" => "Популярные категории",
		"LINE_ELEMENT_COUNT" => "2",
		"LINE_ELEMENT_COUNT_LIST" => "3",
		"LINKED_ELEMENST_PAGE_COUNT" => "20",
		"LINKED_ELEMENT_TAB_SORT_FIELD" => "sort",
		"LINKED_ELEMENT_TAB_SORT_FIELD2" => "id",
		"LINKED_ELEMENT_TAB_SORT_ORDER" => "asc",
		"LINKED_ELEMENT_TAB_SORT_ORDER2" => "desc",
		"LINKED_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "DOOR_2",
			2 => "DOOR_3",
			3 => "",
		),
		"MAX_GALLERY_ITEMS" => "5",
		"MEDIA_PROPERTY" => "",
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "21",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PERIOD_NEW_TAGS" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PRICE_CODE" => "",
		"PRICE_VAT_INCLUDE" => "Y",
		"SALE_STIKER" => "-",
		"SECTIONS_TAGS_DEPTH_LEVEL" => "2",
		"SECTIONS_TYPE_VIEW" => "sections_1",
		"SECTION_ELEMENTS_TYPE_VIEW" => "list_elements_1",
		"SECTION_TYPE_VIEW" => "section_1",
		"SEF_FOLDER" => "/client/features/photoprinting/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SHOW_ASK_BLOCK" => "N",
		"SHOW_BORDER_ELEMENT" => "N",
		"SHOW_CHILD_SECTIONS" => "Y",
		"SHOW_COUNT_ELEMENTS" => "Y",
		"SHOW_DETAIL_LINK" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_DISCOUNT_PERCENT_NUMBER" => "N",
		"SHOW_DISCOUNT_TIME" => "Y",
		"SHOW_FILTER_DATE" => "Y",
		"SHOW_GALLERY_GOODS" => "Y",
		"SHOW_MAX_ELEMENT" => "N",
		"SHOW_MEASURE" => "N",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_ONE_CLICK_BUY" => "Y",
		"SHOW_RATING" => "Y",
		"SHOW_SECTIONS_FILTER" => "Y",
		"SHOW_SECTION_DESCRIPTION" => "Y",
		"SHOW_SECTION_PREVIEW_DESCRIPTION" => "Y",
		"SIDE_LEFT_BLOCK" => "FROM_MODULE",
		"SIDE_LEFT_BLOCK_DETAIL" => "FROM_MODULE",
		"SIZE_IN_ROW" => "4",
		"SLIDER_PROPERTY" => "",
		"SORT_BY1" => "TIMESTAMP_X",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"SORT_REGION_PRICE" => "BASE",
		"STAFF_TYPE_DETAIL" => "list",
		"STIKERS_PROP" => "-",
		"STORES" => array(
			0 => "",
			1 => "",
		),
		"STRICT_SECTION_CHECK" => "N",
		"S_ASK_QUESTION" => "",
		"S_ORDER_SERVISE" => "",
		"TAGS_CLOUD_ELEMENTS" => "150",
		"TAGS_CLOUD_WIDTH" => "100%",
		"TAGS_SECTION_COUNT" => "",
		"TEMPLATE_THEME" => "blue",
		"TITLE_SHOW_FON" => "Y",
		"TIZERS_IBLOCK_ID" => "",
		"TYPE_IMG" => "lg",
		"TYPE_LEFT_BLOCK" => "FROM_MODULE",
		"TYPE_LEFT_BLOCK_DETAIL" => "FROM_MODULE",
		"T_ALSO_ITEMS" => "",
		"T_DOCS" => "",
		"T_GALLERY" => "",
		"T_GOODS" => "",
		"T_MAX_LINK" => "",
		"T_PREV_LINK" => "",
		"T_PROJECTS" => "",
		"T_REVIEWS" => "",
		"T_SERVICES" => "",
		"T_STAFF" => "",
		"T_VIDEO" => "",
		"USE_BG_IMAGE_ALTERNATE" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"USE_SUBSCRIBE_IN_TOP" => "N",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "#SECTION_CODE_PATH#/",
			"detail" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
		)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>