<?php
define('SMARTSEO_MORPHOLOGY_MASCULINUM', 'лп');
define('SMARTSEO_MORPHOLOGY_FEMINUM', 'фп');
define('SMARTSEO_MORPHOLOGY_NEUTRUM', 'яп');
define('SMARTSEO_MORPHOLOGY_NOUN', 'я');
define('SMARTSEO_MORPHOLOGY_ADJ_FULL', 'о');
define('SMARTSEO_MORPHOLOGY_ADJ_SHORT', 'йп_опхк');
define('SMARTSEO_MORPHOLOGY_VERB', 'ц');
define('SMARTSEO_MORPHOLOGY_SINGULAR', 'ед');
define('SMARTSEO_MORPHOLOGY_PLURAL', 'лм');
